// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Models;

#nullable disable

namespace Projekt.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("DepartmentsProducts", b =>
                {
                    b.Property<int>("departmentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("productsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("departmentsId", "productsId");

                    b.HasIndex("productsId");

                    b.ToTable("DepartmentsProducts");

                    b.HasData(
                        new
                        {
                            departmentsId = 2,
                            productsId = 1
                        },
                        new
                        {
                            departmentsId = 2,
                            productsId = 2
                        },
                        new
                        {
                            departmentsId = 2,
                            productsId = 3
                        },
                        new
                        {
                            departmentsId = 2,
                            productsId = 4
                        },
                        new
                        {
                            departmentsId = 2,
                            productsId = 5
                        },
                        new
                        {
                            departmentsId = 2,
                            productsId = 6
                        },
                        new
                        {
                            departmentsId = 2,
                            productsId = 7
                        },
                        new
                        {
                            departmentsId = 1,
                            productsId = 8
                        },
                        new
                        {
                            departmentsId = 1,
                            productsId = 9
                        },
                        new
                        {
                            departmentsId = 1,
                            productsId = 10
                        },
                        new
                        {
                            departmentsId = 1,
                            productsId = 11
                        },
                        new
                        {
                            departmentsId = 3,
                            productsId = 12
                        },
                        new
                        {
                            departmentsId = 3,
                            productsId = 13
                        },
                        new
                        {
                            departmentsId = 3,
                            productsId = 14
                        },
                        new
                        {
                            departmentsId = 4,
                            productsId = 15
                        },
                        new
                        {
                            departmentsId = 4,
                            productsId = 16
                        });
                });

            modelBuilder.Entity("DepartmentsWorker", b =>
                {
                    b.Property<int>("WorkersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("departmentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkersId", "departmentsId");

                    b.HasIndex("departmentsId");

                    b.ToTable("DepartmentsWorker");

                    b.HasData(
                        new
                        {
                            WorkersId = 1,
                            departmentsId = 1
                        },
                        new
                        {
                            WorkersId = 2,
                            departmentsId = 2
                        },
                        new
                        {
                            WorkersId = 3,
                            departmentsId = 3
                        },
                        new
                        {
                            WorkersId = 4,
                            departmentsId = 4
                        });
                });

            modelBuilder.Entity("ProductsSuppliers", b =>
                {
                    b.Property<int>("productsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("suppliersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("productsId", "suppliersId");

                    b.HasIndex("suppliersId");

                    b.ToTable("ProductsSuppliers");

                    b.HasData(
                        new
                        {
                            productsId = 1,
                            suppliersId = 4
                        },
                        new
                        {
                            productsId = 2,
                            suppliersId = 4
                        },
                        new
                        {
                            productsId = 3,
                            suppliersId = 4
                        },
                        new
                        {
                            productsId = 4,
                            suppliersId = 4
                        },
                        new
                        {
                            productsId = 5,
                            suppliersId = 4
                        },
                        new
                        {
                            productsId = 6,
                            suppliersId = 4
                        },
                        new
                        {
                            productsId = 7,
                            suppliersId = 4
                        },
                        new
                        {
                            productsId = 8,
                            suppliersId = 3
                        },
                        new
                        {
                            productsId = 9,
                            suppliersId = 3
                        },
                        new
                        {
                            productsId = 10,
                            suppliersId = 3
                        },
                        new
                        {
                            productsId = 11,
                            suppliersId = 3
                        },
                        new
                        {
                            productsId = 12,
                            suppliersId = 2
                        },
                        new
                        {
                            productsId = 13,
                            suppliersId = 2
                        },
                        new
                        {
                            productsId = 14,
                            suppliersId = 2
                        },
                        new
                        {
                            productsId = 15,
                            suppliersId = 1
                        },
                        new
                        {
                            productsId = 16,
                            suppliersId = 1
                        });
                });

            modelBuilder.Entity("Projekt.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Warzywno-Owocowy"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Napoje i przekąski"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Nabiał"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Mięso i wędliny"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pepsi 2L",
                            Price = 6.5,
                            Quantity = 12.0,
                            Type = "Napój gazowany"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tymbark Jabłkowy 1L",
                            Price = 5.4000000000000004,
                            Quantity = 8.0,
                            Type = "Sok"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cisowianka 1,5 L",
                            Price = 1.8,
                            Quantity = 20.0,
                            Type = "Woda"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lay's Paprykowe",
                            Price = 7.2000000000000002,
                            Quantity = 6.0,
                            Type = "Przekąski"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Doritos Klasyczne",
                            Price = 7.0,
                            Quantity = 10.0,
                            Type = "Przekąski"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Orzeszki Ziemne",
                            Price = 11.199999999999999,
                            Quantity = 7.0,
                            Type = "Przekąski"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Coca-Cola 1,5 L",
                            Price = 8.5,
                            Quantity = 16.0,
                            Type = "Napój gazowany"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Marchewka Polska 1KG",
                            Price = 15.0,
                            Quantity = 16.0,
                            Type = "Warzywa"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Papryka Czerwona 1KG",
                            Price = 26.0,
                            Quantity = 20.0,
                            Type = "Warzywa"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jabłko 1KG",
                            Price = 5.5,
                            Quantity = 25.0,
                            Type = "Owoce"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gruszka 1KG",
                            Price = 12.800000000000001,
                            Quantity = 10.0,
                            Type = "Owoce"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Mleko Łaciate 1L",
                            Price = 4.9900000000000002,
                            Quantity = 12.0,
                            Type = "Nabiał"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ser Półtłusty 250G",
                            Price = 3.9900000000000002,
                            Quantity = 12.0,
                            Type = "Nabiał"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bakoma Natrualny 400G",
                            Price = 5.0,
                            Quantity = 7.0,
                            Type = "Nabiał"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Schab Bez Kości 1KG",
                            Price = 19.5,
                            Quantity = 20.0,
                            Type = "Mięso"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Szynka Drwala 1KG",
                            Price = 37.5,
                            Quantity = 15.0,
                            Type = "Mięso"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Shifts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fhours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fhours = "14:00",
                            Shours = "6:00",
                            Type = "Dzienna"
                        },
                        new
                        {
                            Id = 2,
                            Fhours = "22:00",
                            Shours = "14:00",
                            Type = "Nocna"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Suppliers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carmodel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carmodel = "Iveco Daily",
                            Name = "Sokołów",
                            Type = "Dostawcze"
                        },
                        new
                        {
                            Id = 2,
                            Carmodel = "Fiat Ducato",
                            Name = "Mlekovita",
                            Type = "Dostawcze"
                        },
                        new
                        {
                            Id = 3,
                            Carmodel = "Skoda Octavia",
                            Name = "Sadowcy",
                            Type = "Osobowe"
                        },
                        new
                        {
                            Id = 4,
                            Carmodel = "MAN TGS 18.460",
                            Name = "Eurocash",
                            Type = "Tir"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postalcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul.Krakowska",
                            Age = 30,
                            Lastname = "Nowak",
                            Name = "Jan",
                            Postalcode = "31-004 Kraków"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul.Parkowa",
                            Age = 25,
                            Lastname = "Krzyszczak",
                            Name = "Kuba",
                            Postalcode = "31-004 Kraków"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ul.Bocheńska",
                            Age = 50,
                            Lastname = "Chrostowa",
                            Name = "Janina",
                            Postalcode = "32-000 Niepołomice"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ul.Kazimierza Wielkiego",
                            Age = 42,
                            Lastname = "Kowalska",
                            Name = "Krystyna",
                            Postalcode = "32-700 Bochnia"
                        });
                });

            modelBuilder.Entity("ShiftsWorker", b =>
                {
                    b.Property<int>("shiftsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("workersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("shiftsId", "workersId");

                    b.HasIndex("workersId");

                    b.ToTable("ShiftsWorker");

                    b.HasData(
                        new
                        {
                            shiftsId = 1,
                            workersId = 1
                        },
                        new
                        {
                            shiftsId = 1,
                            workersId = 2
                        },
                        new
                        {
                            shiftsId = 2,
                            workersId = 3
                        },
                        new
                        {
                            shiftsId = 2,
                            workersId = 4
                        });
                });

            modelBuilder.Entity("DepartmentsProducts", b =>
                {
                    b.HasOne("Projekt.Models.Departments", null)
                        .WithMany()
                        .HasForeignKey("departmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Products", null)
                        .WithMany()
                        .HasForeignKey("productsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepartmentsWorker", b =>
                {
                    b.HasOne("Projekt.Models.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Departments", null)
                        .WithMany()
                        .HasForeignKey("departmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsSuppliers", b =>
                {
                    b.HasOne("Projekt.Models.Products", null)
                        .WithMany()
                        .HasForeignKey("productsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Suppliers", null)
                        .WithMany()
                        .HasForeignKey("suppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftsWorker", b =>
                {
                    b.HasOne("Projekt.Models.Shifts", null)
                        .WithMany()
                        .HasForeignKey("shiftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Worker", null)
                        .WithMany()
                        .HasForeignKey("workersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
