// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Models;

#nullable disable

namespace Projekt.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("Projekt.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postalcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul.Krakowska",
                            Age = 30,
                            Lastname = "Nowak",
                            Name = "Jan",
                            Postalcode = "31-004 Kraków"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul.Parkowa",
                            Age = 25,
                            Lastname = "Krzyszczak",
                            Name = "Kuba",
                            Postalcode = "31-004 Kraków"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ul.Bocheńska",
                            Age = 50,
                            Lastname = "Chrostowa",
                            Name = "Janina",
                            Postalcode = "32-000 Niepołomice"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ul.Kazimierza Wielkiego",
                            Age = 42,
                            Lastname = "Kowalska",
                            Name = "Krystyna",
                            Postalcode = "32-700 Bochnia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
